pipeline:
  name: Terraform_IAC_EC2
  identifier: Terraform_IAC_EC2
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Terraform_IAC_github
        repoName: Terraform_IAC_AWS
        build: <+input>
  stages:
    - stage:
        name: Terraform_build
        identifier: Terraform_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      cd EC2
                      terraform init
                      terraform destroy -auto-approve -var="aws_access_key=AKIAYS2NVETRMQZH3DMM" -var="aws_secret_key=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"
                  description: Create EC2 Infrastructure using terraform scripts
